-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 11:42:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_TEMAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_TEMAS` (
  `id` BIGINT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_USUARIO` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TB_POSTAGENS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_POSTAGENS` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` VARCHAR(45) NOT NULL,
  `data` DATE NULL,
  `TB_TEMAS_id` BIGINT NOT NULL,
  `TB_USUARIO_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TB_POSTAGENS_TB_TEMAS_idx` (`TB_TEMAS_id` ASC) VISIBLE,
  INDEX `fk_TB_POSTAGENS_TB_USUARIO1_idx` (`TB_USUARIO_id` ASC) VISIBLE,
  CONSTRAINT `fk_TB_POSTAGENS_TB_TEMAS`
    FOREIGN KEY (`TB_TEMAS_id`)
    REFERENCES `mydb`.`TB_TEMAS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_POSTAGENS_TB_USUARIO1`
    FOREIGN KEY (`TB_USUARIO_id`)
    REFERENCES `mydb`.`TB_USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
